---
ip: "192.168.10.10"
memory: 1024
cpus: 1
provider: virtualbox
box: precise32

folders:
    - map: ~/Code
      to: /home/vagrant/Code

sites:
    - map: site1.dev
      to: /home/vagrant/Code/site1/

# ports:
#     - send: 93000
#       to: 9300
#     - send: 7777
#       to: 777
#       protocol: udp